### ISSUE TITLE
Replace my development server with lite-server

### ISSUE THREAD

**Issue by pford68** [pford68/gulp-scaffold#22]
## TODO
- [x] Add lite-server
- [x] Remove obsolete Gulp tasks.
- [x] Add watchify
- [x] Update browserify task to use watchify
- [x] Update package.json with scripts.dev.
